### ISSUE TITLE
We created a fork using the official python GanetiRapiClient

### ISSUE THREAD

**Issue by geigi** [svalouch/ansible-modules-ganeti#2]
Hey,

first of all, thanks very much for publishing your ganeti_instance module! We use it a lot at our company :) I'm opening an issue here because I couldn't find your email address on your Github profile.
We have created a fork of this module with new features and some more fundamental changes:
* Instead of using `requests` to communicate with the API we use the GanetiRapiClient python library provided by ganeti, which has the benefit of some additional abstraction
* Modification of instances like increasing vCPUs, Memory, ... is possible
* Very simple migration of instances is possible
* We're currently creating a ansible collection to install it with `ansible-galaxy`
* We changed the licence to GPLv3 as this is a requirement for all ansible modules
* There might me some smaller stuff I've forgotten...

If you're interested in merging the code let us know (although a lot of the code has changed). You can have a look at it here:
https://github.com/sipgate/ansible-modules-ganeti

Thanks again :)

EDIT: I forgot to add: creating the ansible collection is still a wip and not finished yet

**Comment by svalouch** [comment]
Hi @geigi, sorry for the delay. I'm happy to hear that the module is useful :) The usage of the GanetiRapiClient looks very promising and I'll look into this soon.

One thing that concerns me a bit is that the GanetiRapiClient doesn't look like it's packaged, so installing this dependency is a bit messy. But it looks like it's the easiest way to get a lot of functionality, on the other hand. Ideally, I'd like the module to work without having to install extra software on top of what most distributions provide, or at least have installable packages for the external dependencies without working around the distributions package manager, and requests is present on most Ansible-equipped hosts anyway. Tough decision.

> We changed the licence to GPLv3 [...]

Well, you can't do that. Changing the license requires permission of all copyright holders.

> [...] as this is a requirement for all ansible modules

So far, I haven't seen the need to change the existing license to GPLv3, unless I have overlooked something. The only place I could find where the GPLv3 is required is if one wants the module to be integrated into and shipped with the official Ansible distribution. Given that Ansible was stripped of most of its modules (which have been moved to community repositories and collections), I doubt that integrating it into the core distribution is an achievable goal. A quick glimpse over the Galaxy did not yield any strict license requirements other than it having to be distributable open source software. So as far as my understanding goes, there is no such requirement imposed by any part of Ansible that's relevant to this module.

**Comment by geigi** [comment]
Thanks for your answer :) 

Regarding the GanetiRapiClient: It is already packaged with the ansible collection: https://github.com/sipgate/ansible-modules-ganeti/blob/master/plugins/module_utils/ganeti_rapi_client.py :) 
But: the library itself requires the python libraries `simplejson` and `pycurl` which need to be present on the machine... This is not perfect as those are not present on every machine.

> Well, you can't do that. Changing the license requires permission of all copyright holders.

Oh I haven't thought about that but you're right. Sorry. What I was thinking was:
The GPLv3 licence says that every code linked to GPLv3 code must be relased under GPLv3 also. Because an ansible module is importing ansible libraries, which is released under GPLv3, I assume the module must be released under GPLv3 also. My assumption is that importing a python library is comparable to linking to a C library. But I don't know if this assumption is correct. If it is, all modules which get distributed or released in any way also must be GPLv3. Maybe this question doesn't have a clear answer. If you wish I can change the licence back to BSD-3.

But I'm happy to hear that you like some ideas of the module.

PS: The module now also has it's first simple tests using a ganeti fake cluster in a docker container using Github Actions!

**Comment by 3c2b2ff5** [comment]
Thank you very much for the plugin. I am wondering if the module can be used to create multiple VM's, or a cluster maybe?

**Comment by svalouch** [comment]
Each declaration of `ganeti_instance` is a single VM, so just repeat the example from the readme (`ganeti_instance` with `state: present`) and you should be good. However, this module isn't maintained any longer, so no guarantee that it even still works in the first place. I guess I should archive it.

Clusters are a whole whole different story and not in any way covered by the module. There's a whole lot of steps to perform and prerequisites to fulfil which is best handled in a playbook on its own, and the final `gnt-cluster init` can then be done using a exec task that makes use of some templating. At least that's how I set it up back in the day.
